### ISSUE TITLE
Structure the data, mini CMS style

### ISSUE THREAD

**Issue by tonynaggs** [dc4420/website#5]
Use an html document for each talk or meeting date etc, to simplify postponing a talk or moving its details from the upcoming event in to the history of past events.

**Comment by Svenito** [comment]
Hello,

After a quick chat with you and (I believe) Mark  @marksteward (?), there was talk about moving to a more talk-per-page set up with a markdown syntax, possibly even jekyll. 

I've taken a bit of time to mock up a quick jekyll site for DC4420 here https://github.com/Svenito/website/tree/jekyll

It's an early idea, and layout, css, and all that will probably need to be tweaked a bit, and not sure this is the kind of direction you wanted to go in.

To test it install jekyll http://jekyllrb.com/docs/installation/ and use `jekyll serve` to start the localhost server.

`_posts` contains two example posts from the original site, so you can see how the markdown looks.

There's no external plugins required. Let me know if you have any questions or anything.

**Comment by marksteward** [comment]
Fixed by #9.
